import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { ReactElement } from 'react'
import { IoPeopleCircle } from 'react-icons/io5'
import Link from 'next/link'
import { BiChat, BiTask } from 'react-icons/bi'
import { HiSparkles } from 'react-icons/hi'
import { FaDumbbell } from 'react-icons/fa'
import { MdHandshake } from 'react-icons/md'
import { BsDiagram3Fill, BsFillChatFill, BsPencilFill, BsPeopleFill } from 'react-icons/bs'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>CollabWrite</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='w-full md:h-[100vh] relative'>

        <div className='w-full h-[70px] relative'>
          <nav className='w-full px-2 md:px-0  xl:w-[1400px] mx-auto h-full flex justify-between items-center'>
            <div className='flex items-center gap-2'>
              <MdHandshake className='text-3xl text-white' />
              <h3 className='font-bold primary-gradient text-transparent bg-clip-text'>CollabWrite</h3>
            </div>
            <Link href="/login" className='p-2 px-4 bg-green-500 text-white font-bold rounded-xl trans hover:text-green-500 hover:bg-white'>Login</Link>
          </nav>
        </div>


        <section className='max-w-[1400px] w-full mx-auto mt-[80px] md:mt-[150px] grid grid-rows-2 grid-cols-1 xl:grid-rows-1 xl:grid-cols-2 relative'>
          {/* <div className='w-[400px] h-[400px] top-[10%] left-[10%] gradient-bg rounded-full absolute'></div>
        <div className='inset-0  backdrop-blur-[100px] absolute'></div> */}
          <div className='flex w-full p-4 flex-col gap-4 relative'>
            <h1 className='text-[2rem] md:text-[3rem]  font-extrabold md:leading-[4.7rem] bg-gradient-to-r  from-green-100 via-green-400 to-yellow-400 bg-clip-text text-transparent'>Harness the power of your mouse and unleash the possibilities within our platform.<span className='bg-gradient-to-r from-green-400 via-yellow-400 to-yellow-400 block text-transparent bg-clip-text background-animate'>CollabWrite.</span></h1>
            <div className='grid grid-cols-2 grid-rows-2 gap-4 mt-5'>
              <Features text={"Manage all your Diagrams"}><BsDiagram3Fill /></Features>
              <Features text={"Go Solo or Collab"}><BsPeopleFill /></Features>
              <Features text={"Draw with your friends in realtime"}><BsPencilFill /></Features>
              <Features text={"Chat with your collaborators in realtime"}><BsFillChatFill /></Features>
            </div>
          </div>
          <div className='w-full flex justify-center relative items-center'>
            <Image src="/ss1.png" height={200} width={320} className='hero-image top-20  z-[100]' alt="" />
            <Image src="/ss2.png" height={200} width={320} className='hero-image bottom-[7rem] left-4  z-[80]' alt="" />
            <Image src="/ss3.png" height={200} width={320} className='hero-image bottom-[9rem] right-5   z-[50]' alt="" />
          </div>
        </section>

      </main>
    </>
  )
}


export const Features = ({ children, text }: { children: any, text: string }) => {
  return (
    <div className='flex gap-3 items-center'>
      <div className='gradient-bg h-10 w-10 md:w-12 md:h-12 rounded-lg grid place-items-center text-white text-xl md:text-3xl'>
        {children}
      </div>
      <p className='text-white/70 font-lilbold text-md'>{text}</p>
    </div>
  )
}